### ISSUE TITLE
Portal and FNaF Wii U

### ISSUE THREAD

**Issue by AlyxFYI** [wikiblog0/Kosmos-Wii-U-Games#1]
Hello!
I'm the project manager and I noticed that you put "Port" but we didn't port these two games we remade it

**Comment by wikiblog0** [comment]
Hello Xyla-TV

Thanks for writing me, the reason why I put the word “port” is because many content creators and various people refer to these games as ports. 

But don't worry I plan to make an update to the repository in the next few days and change the name to: 
“Portal Wii U and FNaF Wii U” as it should be. 

I hope you and the source macchiato team will continue to work on Wii U projects, I appreciate the dedication and effort you put into the Wii U homebrew community.

Regards.

**Comment by AlyxFYI** [comment]
Thank you !
